"use client"

import { createContext, useContext, useState, useEffect, type ReactNode, useMemo } from "react"

// Define available languages
export type Language = "en" | "fr" | "rw"

// Define translation keys structure
type TranslationKeys = {
  [key: string]: string | TranslationKeys
}

// Define translations for each language
const translations: Record<Language, TranslationKeys> = {
  en: {
    auth:{
      congrats: "Your account was succefully created, Check your email or Phone SMS for the CODE and paste it below to activate your Account",
      activate_my_account: "Activate my Account",
      didntreceive: "Didnt Receive Code? ",
      resend: "Resend the Code",
      codeis6: "Auth CODE is 6 Characters",
    },
    nav: {
      dashboard: "Dashboard",
      claims: "My Claims",
      messages: "Messages",
      notifications: "Notifications",
      profile: "Profile",
      logout: "Logout",
    },
    action: {
      new_claim: "New Claim",
      submit: "Submit",
      submit_claim: "Submit Claim",
      submitting: "Submitting...",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      previous: "Previous",
      next: "Next",
      yes: "Yes",
      no: "No",
      upload: "Upload",
      add_photos: "Add Photos",
      clear_all: "Clear All",
      save_and_next: "Save & Next",
      view_details: "View Details",
      remove: "Remove"
    },
    claims: {
      new: "Submit New Claim",
      provide_information: "Please provide all required information",
      basic_info: "Basic Information",
      accident_details: "Accident details and initial report",
      driver_vehicle_info: "Driver & Vehicle Information",
      driver_details: "Driver's details, license information, and vehicle details",
      police_info: "Police Information",
      police_details: "Details about police involvement (Optional)",
      other_vehicles: "Other Vehicles",
      other_vehicles_details: "Information about other vehicles involved",
      injuries_damages: "Injuries and Material Damage",
      injuries: "Injuries",
      damages: "Material Damages",
      injuries_details: "Information about injuries and property damage",
      garage_info: "Garage Information",
      garage_details: "Details about the garage if vehicle is already there",
      documents_photos: "Documents & Photos",
      documents_details: "Upload relevant documents and photos to support your claim",
      police_report_optional:
        "The police report is optional, but providing one may help expedite your claim processing.",
      submission_success: "Claim submitted successfully",
      submission_pending: "Your claim has been submitted and is pending review",
      submission_failed: "Submission failed",
      submission_error: "There was an error submitting your claim",
      validation_error: "Validation Error",
      please_complete_required: "Please complete all required fields before proceeding",
      incomplete_steps: "Incomplete Steps",
      complete_all_steps: "Please complete all steps before submitting your claim",
      active: "Active Claims",
      completed: "Completed Claims",
      total: "Total Claims",
      in_progress: "Claims in progress",
      no_active: "No active claims",
      lifetime: "Lifetime claims",
      progress: "Progress",
      insurer: "Insurer",
      estimated_amount: "Estimated Amount",
      final_amount: "Final Amount",
      no_active_claims: "No Active Claims",
      no_active_message: "You don't have any active claims at the moment",
      no_completed_claims: "No Completed Claims",
      no_completed_message: "You don't have any completed claims yet",
    },
    notifications: {
      unread: "Unread Notifications",
      new_updates: "New Updates",
      recent: "Recent Notifications",
      no_notifications_title: "No Notifications",
      no_notifications_message: "You don't have any notifications at the moment",
      view_all: "View All Notifications",
    },
    form: {
      claim_type: "Claim Type",
      select_claim_type: "Select a Claim type",
      amount_estimated: "Amount u estimate",
      amount_approved: "Amount approved",
      priority: "Priority",
      select_priority: "Select the priority of the claim",
      low: "Low",
      medium: "Medium",
      high: "High",
      policy_number: "Policy Number",
      policy_number_placeholder: "Enter your policy number",
      date: "Date",
      time: "Time",
      location: "Location",
      location_placeholder: "Enter the accident location",
      description: "Accident Description",
      accident_description_placeholder: "Describe how the accident happened in detail",
      pick_date: "Pick a date",
      license_number: "License Number",
      license_number_placeholder: "Enter your driver's license number",
      license_category: "License Category",
      select_category: "Select license category",
      issue_date: "Issue Date",
      driver_surname: "Driver Surname",
      driver_surname_placeholder: "Enter driver's surname",
      driver_name: "Driver Name",
      driver_name_placeholder: "Enter driver's first name",
      driver_phone: "Driver Phone",
      driver_phone_placeholder: "+250 788 123 456",
      vehicle_plate: "Vehicle Plate Number",
      vehicle_plate_placeholder: "Enter vehicle plate number",
      vehicle_model: "Vehicle Model",
      vehicle_model_placeholder: "Enter vehicle model",
      vehicle_make: "Vehicle Make",
      vehicle_make_placeholder: "Enter vehicle make/brand",
      vehicle_year: "Year of Manufacture",
      vehicle_year_placeholder: "Enter year of manufacture",
      accident_date: "Accident Date",
      accident_time: "Accident Time",
      accident_location: "Accident Location",
      accident_description: "Accident Description",
      vehicle_plate_number: "Vehicle Plate Number",
      number_of_other_vehicles: "Number of Other Vehicles",
      damage_owner_name: "Damage Owner Name",
      driver_no_license: "Driver does not have a license",
      police_visited: "Did you visit the police station Or the Police got involved?",
      police_station: "Police Station",
      police_station_placeholder: "Enter police station name",
      police_report_number: "Police Report Number",
      police_report_number_placeholder: "Enter police report number",
      officer_name: "Officer Name",
      officer_name_placeholder: "Enter officer's name",
      officer_phone: "Officer Phone",
      officer_phone_placeholder: "+250 788 123 456",
      other_vehicles_involved: "Were other vehicles involved",
      number_of_vehicles: "Number of Vehicles",
      vehicle_details: "Vehicle {{number}} Details",
      
      plate_number: "Plate Number",
      plate_number_placeholder: "Enter plate number",
      make: "Make",
      make_placeholder: "Enter vehicle make",
      type: "Type",
      type_placeholder: "Enter vehicle type",
      owner_name: "Owner Name",
      owner_name_placeholder: "Enter owner's name",
      owner_surname: "Owner Surname",
      owner_surname_placeholder: "Enter owner's surname",
      owner_address: "Owner Address",
      owner_address_placeholder: "Enter owner's address",
      insurer: "Insurer",
      insurer_placeholder: "Enter insurer name",
      any_injuries: "Were there any injuries",
      number_of_injured: "Number of Injured Persons",
      injured_person_details: "Injured Person {{number}} Details",
      name: "Name",
      name_placeholder: "Enter person's name",
      surname: "Surname",
      surname_placeholder: "Enter person's surname",
      age: "Age",
      age_placeholder: "Enter person's age",
      phone: "Phone",
      phone_placeholder: "+250 788 123 456",
      profession: "Profession",
      profession_placeholder: "Enter person's profession",
      injury_description: "Injury Description",
      injury_description_placeholder: "Describe the injuries in detail",
      check_if_deceased: "the person is deceased?",
      material_damage: "Was there any material damage",
      number_of_damages: "Number of Damaged Items",
      damage_type: "Type of Damage",
      damage_type_placeholder: "Enter type of damage",
      estimated_cost: "Estimated Cost",
      estimated_cost_placeholder: "Estimated cost for the damage",
      damage_owner: "Owner of Damaged Property",
      damage_owner_name_placeholder: "Enter owner's name",
      damage_location: "Location of Damage",
      damage_location_placeholder: "Enter location of damage",
      damage_description: "Damage Description",
      damage_description_placeholder: "Describe the damage in detail",
      in_garage: "Is the vehicle in a garage",
      garage_name: "Garage Name",
      garage_name_placeholder: "Enter garage name",
      garage_address: "Garage Address",
      garage_address_placeholder: "Enter garage address",
      garage_phone: "Garage Phone",
      garage_phone_placeholder: "+250 788 123 456",
      repair_estimate: "Repair Estimate (RWF)",
      repair_estimate_placeholder: "Enter estimated repair cost",
      driver_license: "Driver's License Photo",
      driver_license_description: "Upload a clear photo of both sides of your driver's license",
      vehicle_registration: "Vehicle Registration Photo",
      vehicle_registration_description: "Upload a clear photo of your vehicle registration document",
      accident_scene_photos: "Accident Scene Photos",
      accident_scene_photos_description: "Upload photos of the accident scene from different angles",
      vehicle_damage_photos: "Vehicle Damage Photos",
      vehicle_damage_photos_description: "Upload clear photos showing all damage to your vehicle",
      police_report: "Police Report",
      police_report_description: "Upload the police report if available (PDF, DOC, DOCX)",
      witness_statements: "Witness Statements",
      witness_statements_description: "Upload any witness statements if available",
      additional_documents: "Additional Documents",
      additional_documents_description: "Upload any other relevant documents",
      additional_notes: "Additional Notes",
      additional_notes_placeholder: "Add any additional information that might be relevant to your claim",
      uploaded_files: "Uploaded Files",

      driver_details: "Driver Details",
      has_license: "Has Lincense ?",
      add_driver: "Add Driver",
      vehicle_plate_number_placeholder: "Plate Number, ex: RAJ 111 B",
      add_vehicle: "Add Vehicle",
      vin: "VIN ",
      vin_placeholder: "Vehicle Indentification Number, 17 Characters ",
      police_report_info: "Police report Information",
      police_report_info_details: "Details about Police report",
      add_injury: "Add an Injyury",
      add_damage: "Add a damage", 
      add_garage: "Add a garage",
      garage_details: "Garage details",
      accident_scene_description: "Pictures describing accident scene",
      vehicle_damage_description: "Pictures describing vehicle damage",
      witness_statement_description: "witness statement documents",
      other_description: "Pictures showing more descrition of incident",
      add_police_assignment: "Add Police Info"
    },
    language: {
      select: "Select Language",
      en: "English",
      fr: "French",
      rw: "Kinyarwanda",
    },
    emergency: {
      title: "Emergency Contacts & First Steps",
      subtitle: "Important contacts and actions to take after an accident",
      contacts: "Emergency Contacts",
      ambulance: "Ambulance",
      police: "Police",
      towing: "Towing Service",
      insurance_hotline: "Insurance Hotline",
      first_steps: "First Steps After an Accident",
      ensure_safety: "Ensure everyone's safety and call for medical help if needed",
      take_photos: "Take photos of the accident scene, vehicle damage, and license plates",
      exchange_info: "Exchange contact and insurance information with other parties",
      report_police: "Report to police for documentation (required for insurance)",
      view_full_guide: "View Full Emergency Guide",
    },
    garage: {
      need_recommendations: "Would you like recommendations for nearby garages?",
      recommendations_description: "We can help you find a suitable garage for your vehicle repairs.",
      nearby_garages: "Nearby Garages",
      search_placeholder: "Search by name, location, or services",
      filter: "Filter",
      sort_by: "Sort by",
      distance: "Distance",
      rating: "Rating",
      name: "Name",
      specializations: "Specializations",
      max_distance: "Maximum distance",
      min_rating: "Minimum rating",
      any_rating: "Any rating",
      no_results: "No garages match your criteria. Try adjusting your filters.",
      select: "Select this garage",
      show_recommendations: "Show garage recommendations",
      meters: "m",
      kilometers: "km",
      specialization_bodywork: "Bodywork",
      specialization_mechanical: "Mechanical",
      specialization_electrical: "Electrical",
      specialization_painting: "Painting",
      specialization_diagnostics: "Diagnostics",
    },
  },
  fr: {   auth:{
    congrats: "Your account was succefully created, Check your email or Phone SMS for the CODE and paste it below to activate your Account",
    activate_my_account: "Activate my Account",
    didntreceive: "Didnt Receive Code? ",
    resend: "Resend the Code",
    codeis6: "Auth CODE is 6 Characters",
  },
    nav: {
      dashboard: "Tableau de Bord",
      claims: "Mes Réclamations",
      messages: "Messages",
      notifications: "Notifications",
      profile: "Profil",
      logout: "Déconnexion",
    },
    action: {
      new_claim: "Nouvelle Réclamation",
      submit: "Soumettre",
      submit_claim: "Soumettre la Réclamation",
      submitting: "Soumission en cours...",
      cancel: "Annuler",
      save: "Enregistrer",
      edit: "Modifier",
      delete: "Supprimer",
      previous: "Précédent",
      next: "Suivant",
      yes: "Oui",
      no: "Non",
      upload: "Télécharger",
      add_photos: "Ajouter des Photos",
      clear_all: "Tout Effacer",
      save_and_next: "Enregistrer & Suivant",
      view_details: "Voir les Détails",
      remove: "Enveler"
    },
    claims: {
      new: "Soumettre une Nouvelle Réclamation",
      provide_information: "Veuillez fournir toutes les informations requises",
      basic_info: "Informations de Base",
      accident_details: "Détails de l'accident et rapport initial",
      driver_vehicle_info: "Informations sur le Conducteur et le Véhicule",
      driver_details: "Détails du conducteur, informations sur le permis et détails du véhicule",
      police_info: "Informations de Police",
      police_details: "Détails sur l'implication de la police (Facultatif)",
      other_vehicles: "Autres Véhicules",
      other_vehicles_details: "Informations sur les autres véhicules impliqués",
      injuries_damages: "Blessures et Dommages Matériels",
      injuries: "Les Blessures",
      damages: "Dommages Matériels",
      injuries_details: "Informations sur les blessures et les dommages matériels",
      garage_info: "Informations sur le Garage",
      garage_details: "Détails sur le garage si le véhicule s'y trouve déjà",
      documents_photos: "Documents et Photos",
      documents_details: "Téléchargez les documents et photos pertinents pour appuyer votre réclamation",
      police_report_optional:
        "Le rapport de police est facultatif, mais en fournir un peut aider à accélérer le traitement de votre réclamation.",
      submission_success: "Réclamation soumise avec succès",
      submission_pending: "Votre réclamation a été soumise et est en attente d'examen",
      submission_failed: "Échec de la soumission",
      submission_error: "Une erreur s'est produite lors de la soumission de votre réclamation",
      validation_error: "Erreur de Validation",
      please_complete_required: "Veuillez remplir tous les champs obligatoires avant de continuer",
      incomplete_steps: "Étapes Incomplètes",
      complete_all_steps: "Veuillez compléter toutes les étapes avant de soumettre votre réclamation",
      active: "Réclamations Actives",
      completed: "Réclamations Terminées",
      total: "Total des Réclamations",
      in_progress: "Réclamations en cours",
      no_active: "Aucune réclamation active",
      lifetime: "Réclamations à vie",
      progress: "Progression",
      insurer: "Assureur",
      estimated_amount: "Montant Estimé",
      final_amount: "Montant Final",
      no_active_claims: "Aucune Réclamation Active",
      no_active_message: "Vous n'avez aucune réclamation active pour le moment",
      no_completed_claims: "Aucune Réclamation Terminée",
      no_completed_message: "Vous n'avez pas encore de réclamations terminées",
    },
    notifications: {
      unread: "Notifications Non Lues",
      new_updates: "Nouvelles Mises à Jour",
      recent: "Notifications Récentes",
      no_notifications_title: "Aucune Notification",
      no_notifications_message: "Vous n'avez aucune notification pour le moment",
      view_all: "Voir Toutes les Notifications",
    },
    form: {
      claim_type: "Les type de réclamations",
      select_claim_type: "Selectioner le type de réclamation",
      amount_estimated: "Montant estimé",
      amount_approved: "Montant approuvé",
      priority: "Gravité de la plainte",
      select_priority: "Sélectionnez la gravité de la plainte",
      low: "Bas",
      medium: "Moyen",
      high: "Très élevé",
      policy_number: "Numéro de Police",
      policy_number_placeholder: "Entrez votre numéro de police",
      date: "Date",
      time: "Heure",
      location: "Lieu",
      location_placeholder: "Entrez le lieu de l'accident",
      description: "Description de l'Accident",
      accident_description_placeholder: "Décrivez en détail comment l'accident s'est produit",
      pick_date: "Choisir une date",
      license_number: "Numéro de Permis",
      license_number_placeholder: "Entrez votre numéro de permis de conduire",
      license_category: "Catégorie de Permis",
      select_category: "Sélectionnez la catégorie de permis",
      issue_date: "Date de Délivrance",
      driver_surname: "Nom de Famille du Conducteur",
      driver_surname_placeholder: "Entrez le nom de famille du conducteur",
      driver_name: "Prénom du Conducteur",
      driver_name_placeholder: "Entrez le prénom du conducteur",
      driver_phone: "Téléphone du Conducteur",
      driver_phone_placeholder: "+250 788 123 456",
      vehicle_plate: "Numéro d'Immatriculation",
      vehicle_plate_placeholder: "Entrez le numéro d'immatriculation",
      vehicle_model: "Modèle du Véhicule",
      vehicle_model_placeholder: "Entrez le modèle du véhicule",
      vehicle_make: "Marque du Véhicule",
      vehicle_make_placeholder: "Entrez la marque du véhicule",
      vehicle_year: "Année de Fabrication",
      vehicle_year_placeholder: "Entrez l'année de fabrication",
      accident_date: "Date de l'Accident",
      accident_time: "Heure de l'Accident",
      accident_location: "Lieu de l'Accident",
      accident_description: "Description de l'Accident",
      vehicle_plate_number: "Numéro d'Immatriculation",
      number_of_other_vehicles: "Nombre d'Autres Véhicules",
      damage_owner_name: "Nom du Propriétaire des Dommages",
      driver_no_license: "Le conducteur n'a pas de permis",
      police_visited: "Avez-vous visité le poste de police ou la police est involve",
      police_station: "Poste de Police",
      police_station_placeholder: "Entrez le nom du poste de police",
      police_report_number: "Numéro de Rapport de Police",
      police_report_number_placeholder: "Entrez le numéro du rapport de police",
      officer_name: "Nom de l'Agent",
      officer_name_placeholder: "Entrez le nom de l'agent",
      officer_phone: "Téléphone de l'Agent",
      officer_phone_placeholder: "+250 788 123 456",
      other_vehicles_involved: "D'autres véhicules étaient-ils impliqués",
      number_of_vehicles: "Nombre de Véhicules",
      vehicle_details: "Détails du Véhicule {{number}}",
      plate_number: "Numéro d'Immatriculation",
      plate_number_placeholder: "Entrez le numéro d'immatriculation",
      make: "Marque",
      make_placeholder: "Entrez la marque du véhicule",
      type: "Type",
      type_placeholder: "Entrez le type de véhicule",
      owner_name: "Nom du Propriétaire",
      owner_name_placeholder: "Entrez le nom du propriétaire",
      owner_surname: "Nom de Famille du Propriétaire",
      owner_surname_placeholder: "Entrez le nom de famille du propriétaire",
      owner_address: "Adresse du Propriétaire",
      owner_address_placeholder: "Entrez l'adresse du propriétaire",
      insurer: "Assureur",
      insurer_placeholder: "Entrez le nom de l'assureur",
      any_injuries: "Y a-t-il eu des blessés",
      number_of_injured: "Nombre de Personnes Blessées",
      injured_person_details: "Détails de la Personne Blessée {{number}}",
      name: "Nom",
      name_placeholder: "Entrez le nom de la personne",
      surname: "Nom de Famille",
      surname_placeholder: "Entrez le nom de famille de la personne",
      age: "Âge",
      age_placeholder: "Entrez l'âge de la personne",
      phone: "Téléphone",
      phone_placeholder: "+250 788 123 456",
      profession: "Profession",
      profession_placeholder: "Entrez la profession de la personne",
      injury_description: "Description des Blessures",
      injury_description_placeholder: "Décrivez en détail les blessures",
      check_if_deceased: "la personne est décédée?",
      material_damage: "Y a-t-il eu des dommages matériels",
      number_of_damages: "Nombre d'Articles Endommagés",
      damage_type: "Type de Dommage",
      damage_type_placeholder: "Entrez le type de dommage",
      estimated_cost: "Le Prix estimeer",
      estimated_cost_placeholder: "Entrez le monta estimeer",
      damage_owner: "Propriétaire du Bien Endommagé",
      damage_owner_name_placeholder: "Entrez le nom du propriétaire",
      damage_location: "Lieu du Dommage",
      damage_location_placeholder: "Entrez le lieu du dommage",
      damage_description: "Description du Dommage",
      damage_description_placeholder: "Décrivez en détail le dommage",
      in_garage: "Le véhicule est-il dans un garage",
      garage_name: "Nom du Garage",
      garage_name_placeholder: "Entrez le nom du garage",
      garage_address: "Adresse du Garage",
      garage_address_placeholder: "Entrez l'adresse du garage",
      garage_phone: "Téléphone du Garage",
      garage_phone_placeholder: "+250 788 123 456",
      repair_estimate: "Estimation de Réparation (RWF)",
      repair_estimate_placeholder: "Entrez le coût estimé de réparation",
      driver_license: "Photo du Permis de Conduire",
      driver_license_description: "Téléchargez une photo claire des deux côtés de votre permis de conduire",
      vehicle_registration: "Photo de la Carte Grise",
      vehicle_registration_description: "Téléchargez une photo claire de votre carte grise",
      accident_scene_photos: "Photos de la Scène d'Accident",
      accident_scene_photos_description: "Téléchargez des photos de la scène d'accident sous différents angles",
      vehicle_damage_photos: "Photos des Dommages au Véhicule",
      vehicle_damage_photos_description: "Téléchargez des photos claires montrant tous les dommages à votre véhicule",
      police_report: "Rapport de Police",
      police_report_description: "Téléchargez le rapport de police si disponible (PDF, DOC, DOCX)",
      witness_statements: "Déclarations des Témoins",
      witness_statements_description: "Téléchargez les déclarations des témoins si disponibles",
      additional_documents: "Documents Supplémentaires",
      additional_documents_description: "Téléchargez tout autre document pertinent",
      additional_notes: "Notes Supplémentaires",
      additional_notes_placeholder:
        "Ajoutez toute information supplémentaire qui pourrait être pertinente pour votre réclamation",
      uploaded_files: "Fichiers Téléchargés",

      driver_details: "Les Details du Chauffuer",
      has_license: "a le Lincense ?",
      add_driver: "Ajouter un Chauffuer",
      vehicle_plate_number_placeholder: "Numerau de Plaque, ex: RAJ 111 B",
      add_vehicle: "Ajouter un Vehicle",   
      vin: "VIN ",
      vin_placeholder: "Numereau Indentificateur du Vehicle, 17 Characters ",
      police_report_info: "Les Information du Raport du Police",
      police_report_info_details: "Les Details sure le Raport du Police",
      add_injury: "Ajoute un blessure",
      add_damage: "Ajoute un domage", 
      add_garage: "Ajouter un garage",
      garage_details: "Details sur le garage",
      accident_scene_description: "Photos montrans le scenes d'accident",
      vehicle_damage_description: "Photos montrans les domage du vehicle",
      witness_statement_description: "documents de déclaration de témoin",
      other_description: "Image montrant une description plus détaillée de l'incident",
      add_police_assignment: "Ajouter Police Info"
    },
    language: {
      select: "Choisir la Langue",
      en: "Anglais",
      fr: "Français",
      rw: "Kinyarwanda",
    },
    emergency: {
      title: "Contacts d'Urgence & Premières Étapes",
      subtitle: "Contacts importants et actions à prendre après un accident",
      contacts: "Contacts d'Urgence",
      ambulance: "Ambulance",
      police: "Police",
      towing: "Service de Remorquage",
      insurance_hotline: "Ligne d'Assistance d'Assurance",
      first_steps: "Premières Étapes Après un Accident",
      ensure_safety: "Assurez la sécurité de tous et appelez une aide médicale si nécessaire",
      take_photos: "Prenez des photos du lieu de l'accident, des dommages au véhicule et des plaques d'immatriculation",
      exchange_info: "Échangez les coordonnées et les informations d'assurance avec les autres parties",
      report_police: "Signalez à la police pour documentation (requis pour l'assurance)",
      view_full_guide: "Voir le Guide d'Urgence Complet",
    },
    garage: {
      need_recommendations: "Souhaitez-vous des recommandations de garages à proximité?",
      recommendations_description:
        "Nous pouvons vous aider à trouver un garage adapté pour les réparations de votre véhicule.",
      nearby_garages: "Garages à proximité",
      search_placeholder: "Rechercher par nom, emplacement ou services",
      filter: "Filtrer",
      sort_by: "Trier par",
      distance: "Distance",
      rating: "Évaluation",
      name: "Nom",
      specializations: "Spécialisations",
      max_distance: "Distance maximale",
      min_rating: "Évaluation minimale",
      any_rating: "Toute évaluation",
      no_results: "Aucun garage ne correspond à vos critères. Essayez d'ajuster vos filtres.",
      select: "Sélectionner ce garage",
      show_recommendations: "Afficher les recommandations de garage",
      meters: "m",
      kilometers: "km",
      specialization_bodywork: "Carrosserie",
      specialization_mechanical: "Mécanique",
      specialization_electrical: "Électrique",
      specialization_painting: "Peinture",
      specialization_diagnostics: "Diagnostics",
    },
  },
  rw: {   auth:{
    congrats: "Konti yanyu yafunguwe, reba muri email cg kuri Phone SMS uzane CODE twakoherereje uyishyiremo hano hasi winjiri muri system",
    activate_my_account: "Injira muri konti yanjye",
    didntreceive: "Ntiwabonye Code? ",
    resend: "Ongera uyihabwe Code",
    codeis6: "CODE ninyuguti 6",
  },
    nav: {
      dashboard: "Ibiro",
      claims: "Ubusabe Bwanjye",
      messages: "Ubutumwa",
      notifications: "Imenyesha",
      profile: "Umwirondoro",
      logout: "Gusohoka",
    },
    action: {
      new_claim: "Ubusabe Bushya",
      submit: "Ohereza",
      submit_claim: "Ohereza Ubusabe",
      submitting: "Kohereza...",
      cancel: "Kureka",
      save: "Kubika",
      edit: "Guhindura",
      delete: "Gusiba",
      previous: "Gusubira Inyuma",
      next: "Komeza",
      yes: "Yego",
      no: "Oya",
      upload: "Kohereza",
      add_photos: "Ongeramo Amafoto",
      clear_all: "Gusiba Byose",
      save_and_next: "Kubika & Komeza",
      view_details: "Kureba Birambuye",
      remove: "Kuraho"
    },
    claims: {
      new: "Ohereza Ubusabe Bushya",
      provide_information: "Uzuza amakuru yose asabwa",
      basic_info: "Amakuru y'ibanze",
      accident_details: "Amakuru y'impanuka n'iyandikisha",
      driver_vehicle_info: "Amakuru y'umushoferi n'ikinyabiziga",
      driver_details: "Amakuru y'umushoferi, perimi, n'ikinyabiziga",
      police_info: "Amakuru ya Polisi",
      police_details: "Amakuru y'ubupolisi (Si ngombwa)",
      other_vehicles: "Ibindi binyabiziga",
      other_vehicles_details: "Amakuru y'ibindi binyabiziga byagize uruhare",
      injuries_damages: "Ibikomere n'ibyangirika",
      injuries: "Ibikomere",
      damages: "Ibyangiritse",
      injuries_details: "Amakuru ku bikomere n'ibintu byangiritse",
      garage_info: "Amakuru y'igaraji",
      garage_details: "Amakuru y'igaraji niba ikinyabiziga kirimo",
      documents_photos: "Inyandiko n'Amafoto",
      documents_details: "Ohereza inyandiko n'amafoto biherekeza ubusabe bwawe",
      police_report_optional:
        "Raporo ya polisi ntabwo ari ngombwa, ariko kuyitanga bishobora gufasha kwihutisha gusuzuma ubusabe bwawe.",
      submission_success: "Ubusabe bwoherejwe neza",
      submission_pending: "Ubusabe bwawe bwoherejwe kandi buri gusuzumwa",
      submission_failed: "Ubusabe ntibwoherejwe",
      submission_error: "Hari ikibazo mu kohereza ubusabe bwawe",
      validation_error: "Ikibazo mu Kuzuza",
      please_complete_required: "Nyamuneka uzuza ibisabwa byose mbere yo gukomeza",
      incomplete_steps: "Intambwe Zituzuye",
      complete_all_steps: "Nyamuneka uzuza intambwe zose mbere yo kohereza ubusabe bwawe",
      active: "Ubusabe Bugikora",
      completed: "Ubusabe Bwuzuye",
      total: "Ubusabe Bwose",
      in_progress: "Ubusabe buri gukorwaho",
      no_active: "Nta busabe bugikora",
      lifetime: "Ubusabe bwose",
      progress: "Aho bigeze",
      insurer: "Sosiyeti y'ubwishingizi",
      estimated_amount: "Amafaranga Ateganijwe",
      final_amount: "Amafaranga Yemejwe",
      no_active_claims: "Nta Busabe Bugikora",
      no_active_message: "Nta busabe bugikora ufite kuri ubu",
      no_completed_claims: "Nta Busabe Bwuzuye",
      no_completed_message: "Nta busabe bwuzuye ufite kugeza ubu",
    },
    notifications: {
      unread: "Imenyesha Itarasomwa",
      new_updates: "Imenyesha Nshya",
      recent: "Imenyesha Vuba",
      no_notifications_title: "Nta Menyesha",
      no_notifications_message: "Nta menyesha ufite kuri ubu",
      view_all: "Reba Imenyesha Yose",
    },
    form: {
      claim_type: "Ubwoko Bw'\Ubusabe",
      select_claim_type: "Hitamo Ubwoko Bw'\Ubusabe",
      policy_number: "Nomero y'amasezerano",
      policy_number_placeholder: "Andika nomero y'amasezerano",
      amount_estimated: "Amafranga ukeka ko bikwiye",
      amount_approved: "Amafranga byemejwe ko bikwiye",
      priority: "Ubukana bw'\ikirego",
      select_priority: "Hitamo Ubukana bw'\ikirego",
      low: "Gakeya",
      medium: "Biraringaniye",
      high: "Birakaze cyane",
      date: "Itariki",
      time: "Isaha",
      location: "Aho Impanuka yabereye",
      location_placeholder: "Andika aho impanuka yabereye",
      description: "Ibisobanuro by'impanuka",
      accident_description_placeholder: "Sobanura mu buryo burambuye uko impanuka yabaye",
      pick_date: "Hitamo itariki",
      license_number: "Numero ya perimi",
      license_number_placeholder: "Andika nomero ya perimi yawe",
      license_category: "Ubwoko bwa perimi",
      select_category: "Hitamo ubwoko bwa perimi",
      issue_date: "Itariki yatangiweho",
      driver_surname: "Izina ry'umuryango ry'umushoferi",
      driver_surname_placeholder: "Andika izina ry'umuryango ry'umushoferi",
      driver_name: "Izina ry'umushoferi",
      driver_name_placeholder: "Andika izina ry'umushoferi",
      driver_phone: "Telefoni y'umushoferi",
      driver_phone_placeholder: "+250 788 123 456",
      vehicle_plate: "Plaque y'ikinyabiziga",
      vehicle_plate_placeholder: "Andika plaque y'ikinyabiziga",
      vehicle_model: "Modeli y'ikinyabiziga",
      vehicle_model_placeholder: "Andika modeli y'ikinyabiziga",
      vehicle_make: "Ubwoko bw'ikinyabiziga",
      vehicle_make_placeholder: "Andika ubwoko bw'ikinyabiziga",
      vehicle_year: "Umwaka w'ikorwa",
      vehicle_year_placeholder: "Andika umwaka w'ikorwa",
      accident_date: "Itariki y'Impanuka",
      accident_time: "Igihe cy'Impanuka",
      accident_location: "Aho Impanuka Yabereye",
      accident_description: "Ibisobanuro by'Impanuka",
      vehicle_plate_number: "Nimero y'Ikinyabiziga",
      number_of_other_vehicles: "Umubare w'Ibindi Binyabiziga",
      damage_owner_name: "Izina rya Nyir'Ibyangiritse",
      driver_no_license: "Umushoferi ntafite perimi",
      police_visited: "Wagiye kuri polisi cg police yakurikiranye iyi mpanuka",
      police_station: "Sitasiyo ya Polisi",
      police_station_placeholder: "Andika izina rya sitasiyo ya polisi",
      police_report_number: "Nomero ya Raporo ya Polisi",
      police_report_number_placeholder: "Andika nomero ya raporo ya polisi",
      officer_name: "Izina ry'Umukozi wa Polisi",
      officer_name_placeholder: "Andika izina ry'umukozi wa polisi",
      officer_phone: "Telefoni y'Umukozi wa Polisi",
      officer_phone_placeholder: "+250 788 123 456",
      other_vehicles_involved: "Hari ibindi binyabiziga byagize uruhare",
      number_of_vehicles: "Umubare w'Ibinyabiziga",
      vehicle_details: "Amakuru y'Ikinyabiziga {{number}}",
      plate_number: "Nimero ya Plaque",
      plate_number_placeholder: "Andika nimero ya plaque",
      make: "Ubwoko",
      make_placeholder: "Andika ubwoko bw'ikinyabiziga",
      type: "Ubwoko",
      type_placeholder: "Andika ubwoko bw'ikinyabiziga",
      owner_name: "Izina rya Nyirabyo",
      owner_name_placeholder: "Andika izina rya nyirabyo",
      owner_surname: "Izina ry'Umuryango rya Nyirabyo",
      owner_surname_placeholder: "Andika izina ry'umuryango rya nyirabyo",
      owner_address: "Aderesi ya Nyirabyo",
      owner_address_placeholder: "Andika aderesi ya nyirabyo",
      insurer: "Sosiyeti y'Ubwishingizi",
      insurer_placeholder: "Andika izina rya sosiyeti y'ubwishingizi",
      any_injuries: "Hari abantu bakomeretse",
      number_of_injured: "Umubare w'Abakomeretse",
      injured_person_details: "Amakuru y'Umuntu Wakomeretse {{number}}",
      name: "Izina",
      name_placeholder: "Andika izina ry'umuntu",
      surname: "Izina ry'Umuryango",
      surname_placeholder: "Andika izina ry'umuryango ry'umuntu",
      age: "Imyaka",
      age_placeholder: "Andika imyaka y'umuntu",
      phone: "Telefoni",
      phone_placeholder: "+250 788 123 456",
      profession: "Umwuga",
      profession_placeholder: "Andika umwuga w'umuntu",
      injury_description: "Ibisobanuro by'Ibikomere",
      injury_description_placeholder: "Sobanura mu buryo burambuye ibikomere",
      check_if_deceased: "Uwo umuntu yapfuye?",
      material_damage: "Hari ibintu byangiritse",
      number_of_damages: "Umubare w'Ibintu Byangiritse",
      damage_type: "Ubwoko bw'Ibyangiritse",
      damage_type_placeholder: "Andika ubwoko bw'ibyangiritse",
      estimated_cost: "Agaciro kibyangiritse",
      estimated_cost_placeholder: "Andikamo agaciro kibyangiritse",
      damage_owner: "Nyir'Ibyangiritse",
      damage_owner_name_placeholder: "Andika izina rya nyir'ibyangiritse",
      damage_location: "Aho Ibyangiritse Biri",
      damage_location_placeholder: "Andika aho ibyangiritse biri",
      damage_description: "Ibisobanuro by'Ibyangiritse",
      damage_description_placeholder: "Sobanura mu buryo burambuye ibyangiritse",
      in_garage: "Ikinyabiziga kiri mu igaraji",
      garage_name: "Izina ry'Igaraji",
      garage_name_placeholder: "Andika izina ry'igaraji",
      garage_address: "Aderesi y'Igaraji",
      garage_address_placeholder: "Andika aderesi y'igaraji",
      garage_phone: "Telefoni y'Igaraji",
      garage_phone_placeholder: "+250 788 123 456",
      repair_estimate: "Igiciro Giteganijwe cy'Ikosorwa (RWF)",
      repair_estimate_placeholder: "Andika igiciro giteganijwe cy'ikosorwa",
      driver_license: "Ifoto ya Perimi",
      driver_license_description: "Ohereza ifoto igaragara neza y'impande zombi za perimi yawe",
      vehicle_registration: "Ifoto y'Ikarita y'Ikinyabiziga",
      vehicle_registration_description: "Ohereza ifoto igaragara neza y'ikarita y'ikinyabiziga",
      accident_scene_photos: "Amafoto y'Aho Impanuka Yabereye",
      accident_scene_photos_description: "Ohereza amafoto y'aho impanuka yabereye mu mpande zitandukanye",
      vehicle_damage_photos: "Amafoto y'Ibyangiritse ku Kinyabiziga",
      vehicle_damage_photos_description:
        "Ohereza amafoto agaragara neza yerekana ibyangiritse byose ku kinyabiziga cyawe",
      police_report: "Raporo ya Polisi",
      police_report_description: "Ohereza raporo ya polisi niba ihari (PDF, DOC, DOCX)",
      witness_statements: "Ubuhamya bw'Abatangabuhamya",
      witness_statements_description: "Ohereza ubuhamya bw'abatangabuhamya niba buhari",
      additional_documents: "Izindi Nyandiko",
      additional_documents_description: "Ohereza izindi nyandiko zifite aho zihuriye n'ubusabe",
      additional_notes: "Izindi Nsobanuro",
      additional_notes_placeholder: "Ongeraho andi makuru ashobora kuba afite aho ahuriye n'ubusabe bwawe",
      uploaded_files: "Dosiye Zoherejwe",
      
      driver_details: "Amakuru y'umushoferi",
      has_license: "afite icyangombwa cyo gutwara (perimi) ?",
      add_driver: "Shyiraho Umushoferi",
      vehicle_plate_number_placeholder: "Nimero ya Plake, ex: RAJ 111 B",
      add_vehicle: "Shyiraho Imodoka",
      vin: "VIN",
      vin_placeholder: "Umubare rangakinyabiziga, utugambo 17",
      police_report_info: "Raporo ya Police",
      police_report_info_details: "Amakuru kuri raporo ya Police",
      add_injury: "Shyiraho Invune",
      add_damage: "Shyiraho Ibyangiritse",
      add_garage: "Shyiraho Igaraje",
      garage_details: "Amakuru kw'Igaraje",
    
      accident_scene_description: "Amafoto yerekana ahabereye impanuka",
      vehicle_damage_description: "Amafoto yerekana ibyangiritse kumodoka",
      witness_statement_description: "Inyandiko zubuhamya bwababibonye",
      other_description: "Amafoto yerekana byinshi birambuye kumpanuka",
      add_police_assignment: "Ongeraho Uruhare rwa Police"
    },
    language: {
      select: "Hitamo Ururimi",
      en: "Icyongereza",
      fr: "Igifaransa",
      rw: "Ikinyarwanda",
    },
    emergency: {
      title: "Nimero z'Ubutabazi n'Intambwe za Mbere",
      subtitle: "Nimero z'ingenzi n'ibikorwa bya mbere nyuma y'impanuka",
      contacts: "Nimero z'Ubutabazi",
      ambulance: "Ambulansi",
      police: "Polisi",
      towing: "Serivisi yo Gukurura Imodoka",
      insurance_hotline: "Nimero y'Ubwishingizi",
      first_steps: "Intambwe za Mbere Nyuma y'Impanuka",
      ensure_safety: "Reba ko buri wese ari mu mutekano kandi uhamagare ubufasha bw'abaganga niba bikenewe",
      take_photos: "Fata amafoto y'aho impanuka yabereye, ibyangiritse ku modoka, na plaque",
      exchange_info: "Guhana amakuru n'abandi bantu bari mu mpanuka",
      report_police: "Menyesha polisi kugira ngo handikwe raporo (bikenewe ku bwishingizi)",
      view_full_guide: "Reba Amabwiriza Yuzuye y'Ubutabazi",
    },
    garage: {
      need_recommendations: "Ushaka inama ku byerekeye garagaje ziri hafi?",
      recommendations_description: "Dushobora kugufasha kubona garagaje ikwiye gusana imodoka yawe.",
      nearby_garages: "Garagaje ziri hafi",
      search_placeholder: "Shakisha izina, ahantu, cyangwa serivisi",
      filter: "Filita",
      sort_by: "Tondeka",
      distance: "Intera",
      rating: "Amanota",
      name: "Izina",
      specializations: "Ubuhanga",
      max_distance: "Intera ntarengwa",
      min_rating: "Amanota ntarengwa",
      any_rating: "Amanota yose",
      no_results: "Nta garagaje ihura n'ibyo ushaka. Gerageza guhindura filita zawe.",
      select: "Hitamo iyi garagaje",
      show_recommendations: "Erekana inama za garagaje",
      meters: "m",
      kilometers: "km",
      specialization_bodywork: "Karoseri",
      specialization_mechanical: "Mekaniki",
      specialization_electrical: "Amashanyarazi",
      specialization_painting: "Ipentinga",
      specialization_diagnostics: "Gusuzuma",
    },
  },
}

// Create the language context
interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => { },
  t: (key) => key,
})

// Create the language provider component
interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  // Load saved language preference on mount
  useEffect(() => {
    setMounted(true)
    try {
      const savedLanguage = localStorage.getItem("language") as Language
      if (savedLanguage && ["en", "fr", "rw"].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      }
    } catch (error) {
      console.error("Error loading language from localStorage:", error)
    }
  }, [])

  // Save language preference when it changes
  useEffect(() => {
    if (mounted) {
      try {
        localStorage.setItem("language", language)
      } catch (error) {
        console.error("Error saving language to localStorage:", error)
      }
    }
  }, [language, mounted])

  // Translation function
  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      if (value === undefined) return key
      value = value[k]
    }

    return value || key
  }

  // Create a memoized context value to prevent unnecessary re-renders
  const contextValue = useMemo(
    () => ({
      language,
      setLanguage,
      t,
    }),
    [language],
  )

  return <LanguageContext.Provider value={contextValue}>{children}</LanguageContext.Provider>
}

// Custom hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext)
  return context
}
